# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="sorin"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn tmux)

export PIP2EVAL_TMP_FILE_PATH=/tmp/shm


source $ZSH/oh-my-zsh.sh
source ~/Develop/dotfiles/z/z.sh

bindkey -v
bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^H' backward-delete-char
bindkey '^?' backward-delete-char

fancy-ctrl-z () {
if [[ $#BUFFER -eq 0 ]]; then
    bg
    zle redisplay
  else
    zle push-input
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
bindkey '^U' backward-kill-line

#source zsh-syntax-hightlighting
source ~/Develop/dotfiles/zsh/zsh-syntax-hightlighting/zsh-syntax-highlighting.plugin.zsh
GHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)


# Customize to your needs...
# set -o vi
alias ll='ls -alh'
alias gdd="git add .&&git commit -m 'update'"

alias tmux='tmux -2'

#ssh
alias ssh-aliyun="ssh root@112.124.55.59"
alias ssh-jjs='ssh -i ~/.ssh/test_rsa.rsa -p 38022 ec2-user@jjshouse.com'
alias ssh-cms='ssh -i ~/.ssh/test_rsa.rsa -p 38022 ec2-user@cms-t.dhvalue.com'


#mongo
alias mongo-start="sudo /usr/local/mongo/servers/mongo-start.sh"
alias mongo-openvim="sudo /usr/local/mongo/bin/mongo 127.0.0.1:27017/openvim -uopenvim -p"
alias apa-restart="sudo apachectl restart"


safe_rm () {
  for last; do
    echo $last | grep '^-' >/dev/null 2>&1
    if [[ $? == 1 ]]; then
      if [ -e "$last" ]; then
        file=$(echo $last | awk -F/ '{print $NF}')
        mv $last ~/.local/share/Trash/files/"$file-$(date +%Y-%m-%d-%H-%M-%S)"
      else
        echo "rm: $last: No such file or directory"
      fi
    fi
  done
}

alias rm='safe_rm'


#vim
alias govim="cd ~/.vim"

#alias cd
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."

#mysql to 50-db
alias mysql-dev='mysql -udbuser0114 -pdbpswd0114 -h192.168.1.50'



#unit
alias phpunit="/home/foursk/workspace/jjshouse/v5/vendor/blu3gui7ar/esmeralda/vendor/phpunit/phpunit/phpunit.php"
alias phpunit-coverage="/home/foursk/workspace/jjshouse/v5/vendor/blu3gui7ar/esmeralda/vendor/phpunit/phpunit/phpunit.php --coverage-html"
